--DIM DATE TABLE
SELECT 
[DateKey]
      ,[FullDateAlternateKey] As [Date]
      --,[DayNumberOfWeek]
      ,[EnglishDayNameOfWeek] As [Day]
      --,[SpanishDayNameOfWeek]
      --,[FrenchDayNameOfWeek]
      --,[DayNumberOfMonth]
      --,[DayNumberOfYear]
      ,[WeekNumberOfYear] As [Week Number]
      ,[EnglishMonthName] As [Month]
	  ,LEFT([EnglishMonthName],3) As [Month Short]
      --,[SpanishMonthName]
      --,[FrenchMonthName]
      ,[MonthNumberOfYear] As [Month Number]
      ,[CalendarQuarter] As [Quarter]
      ,[CalendarYear] As [Year]
      --,[CalendarSemester]
      --,[FiscalQuarter]
      --,[FiscalYear]
      --,[FiscalSemester]
  FROM [AdventureWorksDW2022].[dbo].[DimDate]
  WHERE CalendarYear >= 2012