SELECT c.customerKey As Customerkey
      --,[GeographyKey]
      --,[CustomerAlternateKey]
      --,[Title]
      ,c.firstname As [First Name] 
      --,[MiddleName]
      ,c.lastname As [Last Name]
      --,[NameStyle]
      --,[BirthDate]
      --,[MaritalStatus]
      --,[Suffix]
      ,CASE c.gender WHEN 'M' THEN 'MALE' WHEN 'F' THEN 'FEMALE' END As [Gender]
      --,[EmailAddress]
      --,[YearlyIncome]
      --,[TotalChildren]
      --,[NumberChildrenAtHome]
      --,[EnglishEducation]
      --,[SpanishEducation]
      --,[FrenchEducation]
      --,[EnglishOccupation]
      --,[SpanishOccupation]
      --,[FrenchOccupation]
      --,[HouseOwnerFlag]
      --,[NumberCarsOwned]
      --,[AddressLine1]
      --,[AddressLine2]
      --,[Phone]
      ,c.datefirstpurchase As [DateFirstPurchase]
      --,[CommuteDistance]
	  ,g.city as [Customer City]
  FROM [AdventureWorksDW2022].[dbo].[DimCustomer] as c 
  LEFT JOIN dbo.DimGeography as g ON g.GeographyKey = c.GeographyKey
